# This is a basic workflow to help you get started with Actions

name: Run nsr2osm_dump.py every morning

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 05 * * *"
  push:
    branches:    
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run"
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # install the python needed
      - name: 'Kjør nsr2osm_dump.py'
        run: |
          python nsr2osm_dump.py Norge
      
      - name: 'Upload nsr_current.osm'
        uses: actions/upload-artifact@v2
        with:
          name: nsr_current.osm
          path: nsr_current.osm
          retention-days: 7
